### ISSUE TITLE
Cadastramento de livros

### ISSUE THREAD

**Issue by mariaeduardabarboza** [mariaeduardabarboza/SISTEMA-DE-GERENCIAMENTO-DE-UMA-LIVRARIA#1]
Basicamente é uma tarefa para trabalhar no código a parte do cadastramento dos títulos dos livros no sistema e suas respectivas informações de descrição (autor, data de publicação, sinopse, código de identificação e editora). Isso fará com que os dados do acervo bibliográfico da Wizard estejam armazenados e disponibilizados no sistema para que o cliente possa gerenciar a disponibilidade e a quantidade de seus livros, além das informações que especificam cada um.

**Comment by marialuizacosta** [comment]
Podemos implementar na descrição do livro o nivelamento de Inglês no qual este é associado, por exemplo, na Wizard, usamos (KIDS, Teens 2, Teens 2, Teens 6, Teens 8, W10, W12).
